version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  rabbitmq:
    image: rabbitmq:3.12.14-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: betmaker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  bs-bet-maker:
    build:
      context: ./bet_maker_service
      dockerfile: Dockerfile
    container_name: bs-bet-maker
    ports:
      - "8002:8000"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_HOST: rabbitmq
      DB_HOST: postgres
      REDIS_HOST: redis

  bs-line-provider:
    build:
      context: ./line_provider_service
      dockerfile: Dockerfile
    container_name: bs-line-provider
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
